### ISSUE TITLE
building lander fails

### ISSUE THREAD

**Issue by Akitsutori** [msg-DAVID-GmbH/lander#1]
$ make
vendor/github.com/fsouza/go-dockerclient/internal/archive/archive.go:74:20: undefined: idtools.Identity
make: *** [Makefile:6: lander] Error 2

https://github.com/fsouza/go-dockerclient:

>For new projects, using the official SDK is probably more appropriate as go-dockerclient lags behind the official SDK.

see: https://docs.docker.com/develop/sdk/  

----
go version go1.10.7 linux/amd64

**Comment by DerDaehne** [comment]
should be resolved with commit 32f5833 for now.
